//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LionRiver
{
    using System;
    using System.Collections.Generic;
    
    public partial class FleetTrack
    {
        public string Name { get; set; }
        public System.DateTime timestamp { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
        public double COG { get; set; }
        public double SOG { get; set; }
    }
}
