//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LionRiver
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public long Id { get; set; }
        public System.DateTime timestamp { get; set; }
        public long level { get; set; }
        public double LAT { get; set; }
        public double LON { get; set; }
        public Nullable<double> COG { get; set; }
        public Nullable<double> SOG { get; set; }
        public Nullable<double> HDT { get; set; }
        public Nullable<double> TWD { get; set; }
        public Nullable<double> PERF { get; set; }
        public Nullable<double> DPT { get; set; }
        public Nullable<double> TWS { get; set; }
        public Nullable<double> DRIFT { get; set; }
        public Nullable<double> SET { get; set; }
        public Nullable<double> SPD { get; set; }
    }
}
